use_frameworks!

target 'WRCalendarView_Example' do
  pod 'WRCalendarView', :path => '../'
  pod 'DropDownMenuKit'
  
  target 'WRCalendarView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
    pod 'Nimble', '~> 5.1.1'
  end
end
